### ISSUE TITLE
Found an error when lanuch the project with duk-bridge-go 

### ISSUE THREAD

**Issue by woshidama323** [rosbit/duktape-bridge#1]
dlv debug *.go
# exchange-wallet/vendor/github.com/rosbit/duktape-bridge/duk-bridge-go
duk_bridge.c:51:68: warning: format specifies type 'long' but the argument has type 'off_t' (aka 'long long') [-Wformat]
could not launch process: decoding dwarf section info at offset 0x0: too short

**Comment by woshidama323** [comment]
sorry maybe it's not the problem of duk-bridge-go
https://github.com/derekparker/delve/issues/1138

**Comment by rosbit** [comment]
remove the warning by casting off_t to long.
